kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main

steps:
  - name: Publish
    image: plugins/docker
    settings:
      repo: cluster.gov:5000/elsenova
      tags:
        - latest
      registry: cluster.gov:5000
      insecure: true
