kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - master

steps:
  - name: Publish
    image: plugins/docker
    commands:
      - markrawls/elsenova
